### ISSUE TITLE
Access METABASE 0.37 / Firebird

### ISSUE THREAD

**Issue by AntoninoRocha** [evosec/metabase-firebird-driver#10]
Correct the plugin for access (registration) to metabase 0.37, firebird registers but cannot find the tables.

**Comment by AntoninoRocha** [comment]
very important

**Comment by dealanis** [comment]
Hi Antonio, the problem is elsewhere. I have been using this plugin for almost a year and updated Metabase frequently, now running  v0.37.4 without any issues.

Maybe try to debug a little more the logs o attach them on your queries here or on metabase forums.

Best of lucks!

**Comment by AntoninoRocha** [comment]
it may be but it happens when registering the firebird in the new version, who is already registered everything works fine. It is only in the new record in the metabase. If you can create a new record you will find the problem.

**Comment by AntoninoRocha** [comment]
if you can test that you will find the bug

**Comment by AntoninoRocha** [comment]
No suitable driver found, BUG

**Comment by Nikos410** [comment]
Hey everyone,

apologies for taking a while to respond. I've just release [v1.3.0](https://github.com/evosec/metabase-firebird-driver/releases/tag/v1.3.0). That should solve this problem.

If you are still experiencing issues, feel free to reopen this issue :)
