### ISSUE TITLE
user and password are wrong after update

### ISSUE THREAD

**Issue by sebierd** [evosec/metabase-firebird-driver#14]
I've updated the firebird-plugin to v. 1.3. After the update, I get the following error:

_Your user name and password are not defined. Ask your database administrator to set up a Firebird login. [SQLState:28000, ISC error code:335544472]_

I tried to setup a new connection, but the error message stays the same. 

Metabase: 0.38.1
Plugin: 1.3
OS: Ubuntu 18.04.5

**Comment by Nikos410** [comment]
Hm, I'm not sure I can help here. The firebird driver just takes whatever credentials you entered and passes it on to the database. Have you tried connecting to the DB with an SQL client like DBeaver with the same credentials?

**Comment by sebierd** [comment]
> Hm, I'm not sure I can help here. The firebird driver just takes whatever credentials you entered and passes it on to the database. Have you tried connecting to the DB with an SQL client like DBeaver with the same credentials?

I only updated the plugin and metabase. The metabase database (mysql) stays the same.

**Comment by FabriceWork** [comment]
After updating to the latest Firebird driver I am getting the same Error. 
Nothing changed to the Firebird server and I can connect to it just fine with an SQL client using the same credentials used in Metabase.

**Comment by dodgex** [comment]
Maybe it is related to the upgraded jaybird from 3.0.x to 4.0.x.

Maybe the legacy auth stuff mentioned here? https://www.firebirdsql.org/file/documentation/drivers_documentation/java/4.0.0/release_notes.html#removed-legacy_auth-from-default-authentication-plugins

**Comment by FabriceWork** [comment]
> Maybe it is related to the upgraded jaybird from 3.0.x to 4.0.x.
> 
> Maybe the legacy auth stuff mentioned here? https://www.firebirdsql.org/file/documentation/drivers_documentation/java/4.0.0/release_notes.html#removed-legacy_auth-from-default-authentication-plugins

I figured the same so I rebuilt the firebird driver for Metabase 0.38.2 locally with the old jaybird version 3.0.8 and the driver is working again for me.

**Comment by bosborn52** [comment]
@FabriceWork Anyway you could share the rebuilt driver?  I have only figured out how to start building the driver but it is erroring out...

**Comment by FabriceWork** [comment]
> @FabriceWork Anyway you could share the rebuilt driver? I have only figured out how to start building the driver but it is erroring out...

Here is the rebuilt driver, if you still need it. I had to zip it because I can't upload .jar files. 

[firebird.metabase-driver.zip](https://github.com/evosec/metabase-firebird-driver/files/6227360/firebird.metabase-driver.zip)

**Comment by Nikos410** [comment]
Hey @FabriceWork, thanks for your help :)

FYI: I've added an artifact built with Jaybird 3.x to the [latest release](https://github.com/evosec/metabase-firebird-driver/releases/tag/v1.3.0) and plan to do the same for future releases (If I forget, please remind me 😉). I've also added some information about this issue to the README.

**Comment by kumajaya** [comment]
We can still enable Legacy_Auth support with authPlugin connection property, example database name in Metabse: "YOURFIREBIRD3DATABASE?encoding=UTF8&roleName=RDB$ADMIN&authPlugins=Legacy_Auth"

**Comment by Nikos410** [comment]
Hey @kumajaya do you have some documentation on this?

**Comment by kumajaya** [comment]
> Hey @kumajaya do you have some documentation on this?

https://www.firebirdsql.org/file/documentation/drivers_documentation/java/4.0.0/release_notes.html#configure-authentication-plugins

**Comment by Nikos410** [comment]
Thanks @kumajaya ! I've added that to the README section :)
