### ISSUE TITLE
Driver stopped working in 0.32.10

### ISSUE THREAD

**Issue by kumajaya** [evosec/metabase-firebird-driver#2]
Please do an update related to https://github.com/metabase/metabase/commit/e7100252205e01c16daa431f52539dbf8d26c438#diff-d77ef6d7d60b04c2447263a86bfaeabf

Thanks in advance.

**Comment by Nikos410** [comment]
Thanks for the info! Is there documentation somewhere on how exactly the date functions have to look now?

**Comment by kumajaya** [comment]
I'm not sure about it. I only needs a quick fix for my production machine, so I use H2 diver as a reference. I changed line 166 to:

(defmethod driver/date-add :firebird [driver dt amount unit]
  (if (= unit :quarter)
    (recur driver dt (hx/* amount 3) :month)
    (hsql/call :dateadd (hsql/raw (name unit)) amount (hx/cast :timestamp (hx/literal :now)))))

**Comment by Nikos410** [comment]
Thanks! I will look into it when I'm back at the office.

**Comment by Nikos410** [comment]
Please try the latest release, the driver should be working with the current version of Metabase.
