### ISSUE TITLE
Nested queries

### ISSUE THREAD

**Issue by dealanis** [evosec/metabase-firebird-driver#6]
Hi, first of all thanks for making this drive possible for us that use firebird!

Currently I'm trying to use saved questions as data source for new ones, this functionality is possible with other databases but it seems that with my firebird one does not.

Looking around at the driver definition file, it has a sentence that declares "nested-queries" as false. Is this the reason that my questions does not show? Or maybe the issue is on another part?

I tried this with the H2 sample database and postgres one and was able to use saved questions as data sources. My postgres DB is a copy of the firebird one, so the question that want to use is exactly the same.

Using the last version of the driver v1.2 and metabase 0.34.3 .

Thanks for your time!

**Comment by Nikos410** [comment]
Hey there, @dealanis,
thanks fo the heads up!

I have no idea why this feature was disabled, I've enabled it and it seems to work. I have released [Version 1.2.1](https://github.com/evosec/metabase-firebird-driver/releases/tag/v1.2.1), please try if this works for you!
